In [1]:
#https://programmers.co.kr/learn/courses/30/lessons/1843
import numpy as np
import copy

# Idea : 동적계획법
# 행을 i, 열을 j 라 할때 arr의 i번째 항부터 j번째 항까지 계산한 최소값, 최대갑 table 2개를 만들어 연산량을 줄임
# 계산하는 항이 2개일 때는 경우의 수가 1이므로 하나만 계산하여 copy

arr = ["5","-","3","+","1","+","2","-","4"]
update_cnt = int((len(arr)+1)/2)

min_table = []
for i in range(update_cnt):
    min_table.append([0]*update_cnt)
    min_table[i][i] = int(arr[2*i])
    
update_cnt = update_cnt -1
for j in range(update_cnt):
    part = arr[2*j:2*j+3]
    if part[1] == "+":
        value = int(part[0])+int(part[2])
    else:
        value = int(part[0])-int(part[2])
    min_table[j][j+1] = value
max_table = copy.deepcopy(min_table)
print(np.array(max_table))


[[ 5  2  0  0  0]
 [ 0  3  4  0  0]
 [ 0  0  1  3  0]
 [ 0  0  0  2 -2]
 [ 0  0  0  0  4]]


In [2]:
# update_cnt : table에서 update할 원소의 개수
# n_case : update할 당시 고려해야할 경우의 수
# cut_point : 첫번째 괄호의 끝지점
# 연산자가 + 일경우 max_table의 값을 가져올 때가 최대, - 일경우 min_table의 값을 뺄 때가 최대 최소는 반대
# 정답은 max_table의 가장 오른쪽 위의 값

while update_cnt > 1:
    update_cnt = update_cnt - 1
    n_case = int((len(arr)+1)/2) - update_cnt
    for k in range(update_cnt):
        cand = arr[2*k:2*k+2*n_case+1]
        if cand[1] == "+":
            mn = min_table[k][k]+min_table[k+1][k+n_case]
            mx = max_table[k][k]+max_table[k+1][k+n_case]
        else:
            mn = min_table[k][k]-max_table[k+1][k+n_case]
            mx = max_table[k][k]-min_table[k+1][k+n_case]
        for cut_point in range(1,n_case):
            if cand[2*cut_point+1] == '+':
                mn_cand = min_table[k][k+cut_point] + min_table[k+cut_point+1][k+n_case]
                mx_cand = max_table[k][k+cut_point] + max_table[k+cut_point+1][k+n_case]
            else:
                mn_cand = min_table[k][k+cut_point] - max_table[k+cut_point+1][k+n_case]
                mx_cand = max_table[k][k+cut_point] - min_table[k+cut_point+1][k+n_case]
            
            if mn > mn_cand:
                mn = mn_cand
            if mx < mx_cand:
                mx = mx_cand
            
        min_table[k][k+n_case] = mn
        max_table[k][k+n_case] = mx
    print("Iter = %d" %(n_case-1))
    print("min_table")
    print(np.array(min_table))
    print("max_table")
    print(np.array(max_table))
print(max_table[0][int(len(arr)/2)])


Iter = 1
min_table
[[ 5  2  1  0  0]
 [ 0  3  4  6  0]
 [ 0  0  1  3 -1]
 [ 0  0  0  2 -2]
 [ 0  0  0  0  4]]
max_table
[[ 5  2  3  0  0]
 [ 0  3  4  6  0]
 [ 0  0  1  3 -1]
 [ 0  0  0  2 -2]
 [ 0  0  0  0  4]]
Iter = 2
min_table
[[ 5  2  1 -1  0]
 [ 0  3  4  6  2]
 [ 0  0  1  3 -1]
 [ 0  0  0  2 -2]
 [ 0  0  0  0  4]]
max_table
[[ 5  2  3  5  0]
 [ 0  3  4  6  2]
 [ 0  0  1  3 -1]
 [ 0  0  0  2 -2]
 [ 0  0  0  0  4]]
Iter = 3
min_table
[[ 5  2  1 -1 -5]
 [ 0  3  4  6  2]
 [ 0  0  1  3 -1]
 [ 0  0  0  2 -2]
 [ 0  0  0  0  4]]
max_table
[[ 5  2  3  5  3]
 [ 0  3  4  6  2]
 [ 0  0  1  3 -1]
 [ 0  0  0  2 -2]
 [ 0  0  0  0  4]]
3


In [3]:
# 전체 솔루션
def solution(arr):
    update_cnt = int((len(arr)+1)/2)

    min_table = []
    for i in range(update_cnt):
        min_table.append([0]*update_cnt)
        min_table[i][i] = int(arr[2*i])

    update_cnt = update_cnt -1
    for j in range(update_cnt):
        part = arr[2*j:2*j+3]
        if part[1] == "+":
            value = int(part[0])+int(part[2])
        else:
            value = int(part[0])-int(part[2])
        min_table[j][j+1] = value

    max_table = copy.deepcopy(min_table)
    while update_cnt > 1:
        update_cnt = update_cnt - 1
        n_case = int((len(arr)+1)/2) - update_cnt
        for k in range(update_cnt):
            cand = arr[2*k:2*k+2*n_case+1]
            if cand[1] == "+":
                mn = min_table[k][k]+min_table[k+1][k+n_case]
                mx = max_table[k][k]+max_table[k+1][k+n_case]
            else:
                mn = min_table[k][k]-max_table[k+1][k+n_case]
                mx = max_table[k][k]-min_table[k+1][k+n_case]
            for cut_point in range(1,n_case):
                if cand[2*cut_point+1] == '+':
                    mn_cand = min_table[k][k+cut_point] + min_table[k+cut_point+1][k+n_case]
                    mx_cand = max_table[k][k+cut_point] + max_table[k+cut_point+1][k+n_case]
                else:
                    mn_cand = min_table[k][k+cut_point] - max_table[k+cut_point+1][k+n_case]
                    mx_cand = max_table[k][k+cut_point] - min_table[k+cut_point+1][k+n_case]
                if mn > mn_cand:
                    mn = mn_cand
                if mx < mx_cand:
                    mx = mx_cand
            min_table[k][k+n_case] = mn
            max_table[k][k+n_case] = mx
    return(max_table[0][int(len(arr)/2)])
print(solution(arr))

3
