In [105]:
import numpy as np
# 각각 A1 A2 A3 ... A6
matrix_sizes = [[5,2],[2,3],[3,4],[4,6],[6,7],[7,8]]

# idea 동적 계획법
# 행(i) 에서 열(j) 만큼 곱했을 때의 최소값을 차례로 기록
# ex) table[1][3] = A2*A3*A4 의 최소
# 초기 table은 모두 0으로 initialize (table[i][i] = 0)
# cnt : update할 항의 개수 (대각선 방향으로 update)

table = []
cnt = len(matrix_sizes)
for i in range(cnt):
    table.append([0]*cnt)

# table[i][i+1] 은 case가 하나밖에 없으므로 바로 채워줍니다.
cnt = cnt - 1
for i in range(cnt):
    table[i][i+1] = matrix_sizes[i][0]*matrix_sizes[i][1]*matrix_sizes[i+1][1]

print(np.array(table))

[[  0  30   0   0   0   0]
 [  0   0  24   0   0   0]
 [  0   0   0  72   0   0]
 [  0   0   0   0 168   0]
 [  0   0   0   0   0 336]
 [  0   0   0   0   0   0]]


In [106]:
while cnt > 0 :
    cnt = cnt - 1
    # 곱셈을 수행할 행렬의 개수가 2개 이상의 경우는 비교해야 할 case가 생김
    for i in range(cnt):
        # 첫번째 후보로 최소값을 initialize
        n_cases = len(matrix_sizes)-cnt
        min_cand = table[i+1][i+n_cases]+matrix_sizes[i][0]*matrix_sizes[i+1][0]*matrix_sizes[i+n_cases][1]*matrix_sizes[i+n_cases][1]
        # 예를 들어 A2xA3xA4xA5xA6을 한다면 각각
        # (A2) x (A3xA4xA5xA6)
        # (A2xA3) x (A4xA5xA6)
        # (A2xA3xA4) x (A5xA6)
        # (A2xA3xA4xA5) x (A6)
        # 을 비교하며 좌,우 항을 나누는 분기점을 point로 지정, 좌 우 항은 모두 table에 값이 나와 있으므로 index를 잘 설정하여 불러오기
        for point in range(n_cases):
            case = table[i][i+point]+table[i+point+1][i+n_cases]+matrix_sizes[i][0]*matrix_sizes[i+point+1][0]*matrix_sizes[i+n_cases][1]
            if case<min_cand:
                min_cand = case
        table[i][i+n_cases] = min_cand
    print("Iteration %d" % (n_cases-1))
    print(np.array(table))

#정답은 첫번째 행, 마지막 열
print(table[0][len(matrix_sizes)-1])

Iteration 1
[[  0  30  64   0   0   0]
 [  0   0  24  72   0   0]
 [  0   0   0  72 198   0]
 [  0   0   0   0 168 392]
 [  0   0   0   0   0 336]
 [  0   0   0   0   0   0]]
Iteration 2
[[  0  30  64 132   0   0]
 [  0   0  24  72 156   0]
 [  0   0   0  72 198 366]
 [  0   0   0   0 168 392]
 [  0   0   0   0   0 336]
 [  0   0   0   0   0   0]]
Iteration 3
[[  0  30  64 132 226   0]
 [  0   0  24  72 156 268]
 [  0   0   0  72 198 366]
 [  0   0   0   0 168 392]
 [  0   0   0   0   0 336]
 [  0   0   0   0   0   0]]
Iteration 4
[[  0  30  64 132 226 348]
 [  0   0  24  72 156 268]
 [  0   0   0  72 198 366]
 [  0   0   0   0 168 392]
 [  0   0   0   0   0 336]
 [  0   0   0   0   0   0]]
Iteration 4
[[  0  30  64 132 226 348]
 [  0   0  24  72 156 268]
 [  0   0   0  72 198 366]
 [  0   0   0   0 168 392]
 [  0   0   0   0   0 336]
 [  0   0   0   0   0   0]]
348


In [103]:
# 함수화 시키면?
def solution(matrix_sizes):
    table = []
    cnt = len(matrix_sizes)
    for i in range(cnt):
        table.append([0]*cnt)



    cnt = cnt - 1
    for i in range(cnt):
        table[i][i+1] = matrix_sizes[i][0]*matrix_sizes[i][1]*matrix_sizes[i+1][1]

    while cnt > 0 :
        cnt = cnt - 1
        for i in range(cnt):
            n_cases = len(matrix_sizes)-cnt
            min_cand = table[i+1][i+n_cases]+matrix_sizes[i][0]*matrix_sizes[i+1][0]*matrix_sizes[i+n_cases][1]*matrix_sizes[i+n_cases][1]
            for point in range(n_cases):
                case = table[i][i+point]+table[i+point+1][i+n_cases]+matrix_sizes[i][0]*matrix_sizes[i+point+1][0]*matrix_sizes[i+n_cases][1]
                if case<min_cand:
                    min_cand = case
            table[i][i+n_cases] = min_cand

    return(table[0][len(matrix_sizes)-1])


print(solution(matrix_sizes))

348
