In [1]:
import numpy as np
import collections

maps = [[1,0,1,1,1],[1,0,1,0,1],[1,0,1,1,1],[1,1,1,0,1],[0,0,0,0,1]]
n_row = len(maps)
n_col = len(maps[0])


# table : 각 칸에 도달했을 때 최소 몇 번째 움직임 만에 도달했는가?
table = []
for _ in range(n_row):
    table.append([-2]*n_col)

# queue의 원소 : [row,col,최소 도착 횟수(cnt)]
start = [0,0,0]

queue = collections.deque([start])
while queue:
    # 최소 거리를 구해야 하기 때문에 queue의 앞에서부터 체크한다.(BFS)
    now = queue.popleft()
    row, col, cnt = now
    table[row][col] = cnt
    
    nxt = []
    if row > 0 and maps[row-1][col] == 1:
        nxt.append([row-1,col])
    if row < n_row-1 and maps[row+1][col] == 1:
        nxt.append([row+1,col])
    if col > 0 and maps[row][col-1] == 1:
        nxt.append([row,col-1])
    if col < n_col-1 and maps[row][col+1]:
        nxt.append([row,col+1])
    
    for n in nxt:
    # 보통 BFS 문제는 visited를 활용하여 체크를 하는 문제가 많으나 여기서는 지나갔던 곳일 경우 map의 숫자를 0으로 바꾸어 기록하여
    # 시간을 단축할수 있다.
        maps[n[0]][n[1]]=0
        n.append(cnt+1)
        if n not in queue:
            queue.append(n)
    # 각 iteration마다 queue와 cnt_table
    print(queue)
    print(np.array(table))
    #도착지점의 값 + 1을 반환
    print(table[n_row-1][n_col-1]+1)

deque([[1, 0, 1]])
[[ 0 -2 -2 -2 -2]
 [-2 -2 -2 -2 -2]
 [-2 -2 -2 -2 -2]
 [-2 -2 -2 -2 -2]
 [-2 -2 -2 -2 -2]]
-1
deque([[0, 0, 2], [2, 0, 2]])
[[ 0 -2 -2 -2 -2]
 [ 1 -2 -2 -2 -2]
 [-2 -2 -2 -2 -2]
 [-2 -2 -2 -2 -2]
 [-2 -2 -2 -2 -2]]
-1
deque([[2, 0, 2]])
[[ 2 -2 -2 -2 -2]
 [ 1 -2 -2 -2 -2]
 [-2 -2 -2 -2 -2]
 [-2 -2 -2 -2 -2]
 [-2 -2 -2 -2 -2]]
-1
deque([[3, 0, 3]])
[[ 2 -2 -2 -2 -2]
 [ 1 -2 -2 -2 -2]
 [ 2 -2 -2 -2 -2]
 [-2 -2 -2 -2 -2]
 [-2 -2 -2 -2 -2]]
-1
deque([[3, 1, 4]])
[[ 2 -2 -2 -2 -2]
 [ 1 -2 -2 -2 -2]
 [ 2 -2 -2 -2 -2]
 [ 3 -2 -2 -2 -2]
 [-2 -2 -2 -2 -2]]
-1
deque([[3, 2, 5]])
[[ 2 -2 -2 -2 -2]
 [ 1 -2 -2 -2 -2]
 [ 2 -2 -2 -2 -2]
 [ 3  4 -2 -2 -2]
 [-2 -2 -2 -2 -2]]
-1
deque([[2, 2, 6]])
[[ 2 -2 -2 -2 -2]
 [ 1 -2 -2 -2 -2]
 [ 2 -2 -2 -2 -2]
 [ 3  4  5 -2 -2]
 [-2 -2 -2 -2 -2]]
-1
deque([[1, 2, 7], [2, 3, 7]])
[[ 2 -2 -2 -2 -2]
 [ 1 -2 -2 -2 -2]
 [ 2 -2  6 -2 -2]
 [ 3  4  5 -2 -2]
 [-2 -2 -2 -2 -2]]
-1
deque([[2, 3, 7], [0, 2, 8]])
[[ 2 -2 -2 -2 -2]
 [ 1 -2  7 -2 -2]
 [ 2 -2 

In [2]:
#솔루션화하면
import collections
maps = [[1,0,1,1,1],[1,0,1,0,1],[1,0,1,1,1],[1,1,1,0,1],[0,0,0,0,1]]

def solution(maps):
    start = [0,0,0]
    n_row = len(maps)
    n_col = len(maps[0])

    table = []
    for _ in range(n_row):
        table.append([-2]*n_col)

    queue = collections.deque([start])
    while queue:
        now = queue.popleft()
        row, col, cnt = now
        table[row][col] = cnt
        nxt = []
        if row > 0 and maps[row-1][col] == 1:
            nxt.append([row-1,col])
        if row < n_row-1 and maps[row+1][col] == 1:
            nxt.append([row+1,col])
        if col > 0 and maps[row][col-1] == 1:
            nxt.append([row,col-1])
        if col < n_col-1 and maps[row][col+1]:
            nxt.append([row,col+1])

        for n in nxt:
            maps[n[0]][n[1]]=0
            n.append(cnt+1)
            if n not in queue:
                queue.append(n)

    return(table[n_row-1][n_col-1]+1)
solution(maps)

11