In [1]:
# table 행 : n, 열 : 열린 괄호 cnt 개로 시작하는 올바른 괄호의 개수
# ex : table(5,3) = 5개의 괄호 쌍 중 ((( 로 시작하는 올바른 괄호의 개수
# Iter 1 : n개의 괄호 쌍 중 n개의 열린 괄호로 시작하는 올바른 괄호의 개수는 무조건 1 (나머지가 모두 닫힌 괄호)
# Iter 2 : n개의 괄호 쌍 중 n-1개의 열린 괄호로 시작하는 올바른 괄호의 개수는 무조건 n (n개의 닫힌 괄호 사이 중 1군데에 열린 괄호가
# 들어감, 맨 마지막 자리는 들어갈 수 없음)
# Iter n (코드 변수명 update), cnt = 1 (코드에서 j==0) :
# table(n,1) = (~~~~ = ()~~~~ + ((~~~~ = table(n-1,1) + table(n,2)
# Iter n , cnt != 1 (코드에서 else) :
# table(n,cnt) = (((~~~~ = ((()~~~~ + ((((~~~~ = table(n-1,cnt-1) + table(n,cnt+1)
# table을 모두 채우면 table(n,1)값을 반환

import numpy as np


def solution(n):
    if n == 1:
        return(1)
    
    table = []
    for i in range(n):
        table.append([0]*n)
        table[i][i] = 1
        if i >0:
            table[i][i-1] = i+1
            
    cnt = n-2
    while cnt > 0:
        update = n - cnt
        for j in range(cnt):
            if j == 0:
                table[update][0] = table[update-1][0]+table[update][1]
            else:
                table[j+update][j] = table[j+update-1][j-1]+table[j+update][j+1]
        cnt = cnt - 1
    
    print(np.array(table))
    answer = table[n-1][0]
    return answer

solution(5)

[[ 1  0  0  0  0]
 [ 2  1  0  0  0]
 [ 5  3  1  0  0]
 [14  9  4  1  0]
 [42 28 14  5  1]]


42